project_id = "txilwgpfxgjklptrwjjd"

[functions.create-razorpay-order]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.create-razorpay-qr]
verify_jwt = false

[functions.check-qr-payment]
verify_jwt = false